resolver: lts-14.7
packages:
- '.'
extra-deps:
- extensible-0.6.1
- membership-0
- binary-instances-1
- github: matsubara0507/mix.hs
  commit: 4978a33dec736799b30c14e215f7fa0f29fa2884
  subdirs:
  - mix
  - mix-plugin-github
- github: matsubara0507/github
  commit: 0e53921d2433c3e86b7231e6be7d234ae75c095f
- github: matsubara0507/fallible
  commit: dfbdce1a0b0c71bcfcea844c94f9cb815f071235

docker:
  repo: matsubara0507/stack-build
  enable: false
