name: Build

on:
  pull_request: null
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        ghc: ["8.6.5"]
        cabal: ["3.0"]
        cache-version: ["v1"]

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Cache .stack
      id: cache-stack
      uses: actions/cache@v1
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml.lock') }}-${{ matrix.cache-version }}
        restore-keys: |
          ${{ runner.os }}-stack-

    - name: Cache .stack/pantry
      id: cache-pantry
      uses: actions/cache@v1
      with:
        path: ~/.stack-temp/pantry
        key: ${{ runner.os }}-pantry-${{ hashFiles('**/stack.yaml.lock') }}-${{ matrix.cache-version }}
        restore-keys: |
          ${{ runner.os }}-pantry-

    - name: Cache .stack/programs
      id: cache-programs
      uses: actions/cache@v1
      with:
        path: ~/.stack-temp/programs
        key: ${{ runner.os }}-programs-${{ hashFiles('**/stack.yaml.lock') }}-${{ matrix.cache-version }}
        restore-keys: |
          ${{ runner.os }}-programs-

    - name: Cache .stack-work
      id: cache-work
      uses: actions/cache@v1
      with:
        path: .stack-work
        key: ${{ runner.os }}-local-stack-${{ hashFiles('**/stack.yaml.lock') }}
        restore-keys: |
          ${{ runner.os }}-local-stack

    - name: Move .stack/pantry to temp
      uses: matsubara0507/actions/move-files@master
      with:
        source_dir: ~/.stack-temp/pantry
        source_files: |
          pantry
        target_dir: ~/.stack

    - name: Move .stack/programs to temp
      uses: matsubara0507/actions/move-files@master
      with:
        source_dir: ~/.stack-temp/programs
        source_files: |
          programs
        target_dir: ~/.stack

    - uses: actions/setup-haskell@v1
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - uses: mstksg/setup-stack@v1

    - name: Install dependencies
      run: stack build --only-dependencies

    - name: Build binary
      run: stack install --local-bin-path=./bin

    - name: Display .stack size
      run: |
        du -sh ~/.stack/*
        du -sh ~/.stack/programs/x86_64-linux/*
        du -sh .stack-work/*
