name: Build

on:
  pull_request: null
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        ghc: ["8.6.5"]
        cabal: ["3.0"]

    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1

    - name: Cache .stack pantry
      uses: actions/cache@v1
      with:
        path: ~/.stack/pantry
        key: ${{ runner.os }}-stack-pantry-${{ hashFiles('**/stack.yaml.lock') }}
        restore-keys: |
          ${{ runner.os }}-stack-pantry-

    - uses: actions/setup-haskell@v1
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - uses: mstksg/setup-stack@v1

    - name: Install dependencies
      run: stack --docker build --only-dependencies

    - name: Build binary
      run: stack --docker install --local-bin-path=./bin

    - name: Debug
      run: du -sh ~/.stack/*
